django_clouding_unarchive/urls.py
from django.urls import path
from .views import UnarchiveView, StatusView, IsActiveView, ServerIsReadyView, ServerNameView

app_name = "django_clouding_unarchive"

urlpatterns = [
    path("server-status/", StatusView.as_view(), name="server-status"),
    path("unarchive-server/", UnarchiveView.as_view(), name="unarchive-server"),
    path("server-is-active/", IsActiveView.as_view(), name="server-is-active"),
    path("server-is-ready/", ServerIsReadyView.as_view(), name="server-is-ready"),
    path("server-name/", ServerNameView.as_view(), name="server-name"),
]

django_clouding_unarchive/views.py
import requests
from django.http import HttpResponse, HttpResponseBadRequest
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ImproperlyConfigured
from django.views import View
from .api_models import CloudingAPI
from .exceptions import CloudingAPIError
from requests.exceptions import ConnectionError


class CloudingAPIView(LoginRequiredMixin, View):

    def get_server(self, request):
        server_id = request.GET.get('server_id')
        return CloudingAPI(server_id=server_id)


class IsActiveView(CloudingAPIView):
    def get(self, request):
        try:
            server = self.get_server(request)
        except ImproperlyConfigured as e:
            return HttpResponseBadRequest(str(e))
        try:
            if server.is_active():
                return HttpResponse('active')
            return HttpResponse('inactive')
        except CloudingAPIError as e:
            return HttpResponseBadRequest(str(e))


class UnarchiveView(CloudingAPIView):
    def get(self, request):
        try:
            server = self.get_server(request)
        except ImproperlyConfigured as e:
            return HttpResponseBadRequest(str(e))
        try:
            return HttpResponse(server.unarchive())
        except CloudingAPIError as e:
            return HttpResponseBadRequest(str(e))


class StatusView(CloudingAPIView):
    def get(self, request):
        try:
            server = self.get_server(request)
        except ImproperlyConfigured as e:
            return HttpResponseBadRequest(str(e))
        try:
            return HttpResponse(server.get_status())
        except CloudingAPIError as e:
            return HttpResponseBadRequest(str(e))


class ServerIsReadyView(CloudingAPIView):
    def get(self, request):
        url = request.GET.get('url')
        try:
            if not url:
                return HttpResponseBadRequest('url parameter is required')
            response = requests.head(url)
            return HttpResponse('ready' if response.ok else 'not ready')
        except ConnectionError:
            return HttpResponse('not ready')


class ServerNameView(CloudingAPIView):
    def get(self, request):
        try:
            server = self.get_server(request)
            return HttpResponse(server.name)
        except ImproperlyConfigured as e:
            return HttpResponseBadRequest(str(e))
        except CloudingAPIError as e:
            return HttpResponseBadRequest(str(e))

django_clouding_unarchive/templates/django_clouding_unarchive/button.html
<style>
    .django-unarchive-wrapper {
        margin: 10px;
    }

    .django-unarchive {
        all: unset;
        display: flex;
        flex-wrap: wrap;
        align-items: center;
        gap: 1rem;
        padding: 10px;
        border: none;
        margin: 10px;
        border-radius: 4px;
        color: var(--button-fg);
        background: var(--button-bg);
        min-height: 40px;
        max-width: 200px;
        user-select: none;
        min-width: 150px;
    }

    .django-unarchive:hover, .django-unarchive:disabled  {
        border: none;
        color: var(--button-hover-fg);
        background: var(--button-hover-bg);
    }

    .django-unarchive[data-ready="ready"] {
        background: green;
        cursor: pointer;
    }

    .django-unarchive[data-status="Archived"] {
        cursor: pointer;
    }

    .django-unarchive .loader {
        width: 24px;
        height: auto;
        margin-left: auto;
        display: none;
    }
</style>

<div class="django-unarchive-wrapper">
    <button
        type="button"
        id="button_id"
        class="django-unarchive {{ css_classes }}"
        data-on-success-url="{{ on_success_url }}"
        data-test-on-success-url="{% if test_on_success_url %}test{% endif %}"
        data-status-url="{% url 'django_clouding_unarchive:server-status' %}{% if server_id %}?server_id={{ server_id }}{% endif %}"
        data-unarchive-url="{% url 'django_clouding_unarchive:unarchive-server' %}{% if server_id %}?server_id={{ server_id }}{% endif %}"
        data-server-name-url="{% url 'django_clouding_unarchive:server-name' %}{% if server_id %}?server_id={{ server_id }}{% endif %}"
        data-server-name="{{ server_name }}"
        data-setup=""
        data-status="first_query"
        data-error-message=""
        data-ready="">
        <div class="server_status_display">Loading…</div>
        <!-- Loader credits: Nikhil Krishnan https://codepen.io/nikhil8krishnan/pen/rVoXJa Added start animations on click button (begin="indefinite") and begin on button click by javascript function 'animate_clock(button)' -->
        <svg class="loader" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 100 100" enable-background="new 0 0 100 100" xml:space="preserve">
            <circle fill="#ddd" stroke="#fff" stroke-width="12" stroke-miterlimit="10" cx="50" cy="50" r="42"/>
            <line fill="none" stroke-linecap="round" stroke="#777" stroke-width="8" stroke-miterlimit="10" x1="50" y1="50" x2="50" y2="16">
            <animateTransform attributeName="transform" dur="2s" type="rotate" from="0 50 50" to="360 50 50" begin="indefinite" repeatCount="indefinite" />
            </line>
            <line fill="none" stroke-linecap="round" stroke="#777" stroke-width="8" stroke-miterlimit="10" x1="50" y1="50" x2="50" y2="24">
            <animateTransform attributeName="transform" dur="60s" type="rotate" from="0 50 50" to="360 50 50" begin="indefinite" repeatCount="indefinite" />
            </line>
        </svg>
    </button>
</div>
  
<script type="module">
    function show_loader(button){
        // Start the loader animation
        let elements = button.getElementsByTagName("animateTransform");
        for (let element of elements)
            element.beginElement();
        
        // Show the loader
        let loader = button.querySelector('.loader');
        loader.style.display = 'block';
    }
    

    function hide_loader(button){
        let loader = button.querySelector('.loader');
        loader.style.display = 'none';
    }


    function display_status(button){
        let server_status_display = button.querySelector('.server_status_display');
        let status = button.dataset.status;
        let url = button.dataset.onSuccessUrl;
        let url_need_test = button.dataset.testOnSuccessUrl != "";
        let ready = button.dataset.ready;

        if (status == "Error"){
            hide_loader(button);
            button.disabled = false;
            if(button.dataset.errorMessage)
                server_status_display.innerHTML = `Error: ${button.dataset.errorMessage}`;
            else
                server_status_display.innerHTML = `Try again later`;
            return;
        }

        let active = status == "Active";
        if (active && url && (url_need_test && ready || !url_need_test)){
            server_status_display.innerHTML = `Click to view`;
            button.disabled = false;
        } else if (active && url && url_need_test && !ready){
            button.disabled = true;
            server_status_display.innerHTML = `Almost ready…`;
        } else if (active){
            server_status_display.innerHTML = `Active`; // when we don't have a success url.
            button.disabled = true;
        } else if (status == "Archived"){
            button.disabled = false;
            server_status_display.innerHTML = `Wake it up`;
        } else if (status == "Archiving"){
            button.disabled = true;
            server_status_display.innerHTML = `Going to sleep…`;
        } else {
            button.disabled = true;
            server_status_display.innerHTML = `Waking up…`;
        }
    }


    function update_status_until_ready(button){
        let server_status_display = button.querySelector('.server_status_display');
        let url = button.dataset.onSuccessUrl;
        fetch('{% url "django_clouding_unarchive:server-is-ready" %}?url=' + encodeURIComponent(url))
        .then(response => response.text())
        .then(text => {
            if (text == "ready"){
                button.dataset.ready = "ready";
                display_status(button);
                hide_loader(button);
            } else {
                button.dataset.ready = "";
                display_status(button);
                setTimeout(() => update_status_until_ready(button), 5000);
            }
        }).catch(err => {
            console.log(err);
            button.dataset.ready = "";
            button.dataset.status = "Error";
            hide_loader(button);
            display_status(button);
        });
    }


    // Documentation: https://api.clouding.io/docs#tag/Servers/operation/GetServerById
    let done_states = ["Active", "Archived", "Stopped", "Deleted", "Error", "Unknown"]; 
    
    function update_status_until_done(button){
        fetch(button.dataset.statusUrl)
        .then(response => { 
            if(!response.ok)
                return Promise.reject(response);
            
            return response.text()
        })
        .then(response_text => {
            console.log(`${button.dataset.serverName} is ${response_text}`);
            let first_query = button.dataset.status == "first_query";
            button.dataset.status = response_text;
            
            if (!done_states.includes(response_text)){
                if (first_query)
                    show_loader(button);
                display_status(button);
                setTimeout(() => update_status_until_done(button), 5000);
            } else if (response_text == "Active" && button.dataset.onSuccessUrl && button.dataset.testOnSuccessUrl){
                if (first_query)
                    show_loader(button);
                display_status(button);
                update_status_until_ready(button);
            } else if (response_text == "Active" && button.dataset.onSuccessUrl){
                button.dataset.ready = "ready";
                display_status(button);
                hide_loader(button);
            } else {
                display_status(button);
                hide_loader(button);
            }
        }).catch(response => {
            console.log(response);
            button.dataset.status = "Error";
            if(response.status == 500){
                button.dataset.errorMessage = "Internal Server Error";
                display_status(button);
                button.disabled = false;
            } else
                response.text().then(text => {
                    button.dataset.errorMessage = text;
                    display_status(button);
                    button.disabled = false;
                });            
        });
    }


    for (let button of document.querySelectorAll('button.django-unarchive')){
        if (button.dataset.setup == "setup")
            continue;

        button.dataset.setup = "setup";
        button.addEventListener("click", event => {
            let button = event.currentTarget;
            if (button.dataset.ready){
                console.log("url: ", button.dataset.onSuccessUrl);
                window.open(button.dataset.onSuccessUrl, '_blank');
                return;
            }
            show_loader(button);
            button.disabled = true;
            fetch(button.dataset.unarchiveUrl)
            .then(response => response.text())
            .then(response_text => {
                console.log(response_text);
                update_status_until_done(button);
            }).catch(err => {
                console.log(err);
                button.dataset.status = "Error";
                display_status(button);
                button.disabled = false;
            });
        });
        
        if (!button.dataset.serverName)
            fetch(button.dataset.serverNameUrl)
            .then(response => response.text())
            .then(response_text => {
                button.dataset.serverName = response_text;
            }).catch(err => {
                console.log(err);
            });
        
        update_status_until_done(button);
    }
</script>